package Model;
// Generated 6 mai 2018 18:06:59 by Hibernate Tools 4.3.1



import java.util.Date;
import java.util.HashSet;

import java.util.Set;

/**
 * Prescriptionentet generated by hbm2java
 */
public class Prescriptionentet  implements java.io.Serializable {


     private int codePrescription;
     private Tiers Patient;
     private Date datePrescription;
     private String organisation;
     private Tiers Auteur;
     private String observation;
     private Set<PrescriptionDetail> detail=new HashSet<PrescriptionDetail>();
    public Prescriptionentet() {
    }

    public void setDetail(Set<PrescriptionDetail> detail) {
        this.detail = detail;
    }

    public Set<PrescriptionDetail> getDetail() {
        return detail;
    }

	

    public Prescriptionentet(int codePrescription, Tiers Patient, Date datePrescription, String organisation, Tiers Auteur, String observation) {
       this.codePrescription = codePrescription;
       this.Patient = Patient;
       this.datePrescription = datePrescription;
       this.organisation = organisation;
       this.Auteur = Auteur;
       this.observation = observation;
    }
   
    public int getCodePrescription() {
        return this.codePrescription;
    }
    
    public void setCodePrescription(int codePrescription) {
        this.codePrescription = codePrescription;
    }
  
    public Date getDatePrescription() {
        return this.datePrescription;
    }
    
    public void setDatePrescription(Date datePrescription) {
        this.datePrescription = datePrescription;
    }
    public String getOrganisation() {
        return this.organisation;
    }
    
    public void setOrganisation(String organisation) {
        this.organisation = organisation;
    }
 
    public String getObservation() {
        return this.observation;
    }
    
    public void setObservation(String observation) {
        this.observation = observation;
    }

    public Tiers getPatient() {
        return Patient;
    }

    public void setPatient(Tiers Patient) {
        this.Patient = Patient;
    }

    public void setAuteur(Tiers Auteur) {
        this.Auteur = Auteur;
    }

    public Tiers getAuteur() {
        return Auteur;
    }


}


