package Model;
// Generated 6 mai 2018 18:06:59 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tiers generated by hbm2java
 */
public class Tiers  implements java.io.Serializable {


     private String nss;
     private String nom;
     private String prenom;

    public Set<Prescriptionentet> getPrescriptions() {
        return prescriptions;
    }

    public void setPrescriptions(Set<Prescriptionentet> prescriptions) {
        this.prescriptions = prescriptions;
    }


     private String adress;
     private Date datenaissance;
    private Set<Prescriptionentet> prescriptions=new HashSet<Prescriptionentet>();
    private Set<Prescriptionentet> Redigedprescriptions=new HashSet<Prescriptionentet>();
    public Tiers() {
        super();
    }

    public void setRedigedprescriptions(Set<Prescriptionentet> Redigedprescriptions) {
        this.Redigedprescriptions = Redigedprescriptions;
    }

    public Set<Prescriptionentet> getRedigedprescriptions() {
        return Redigedprescriptions;
    }

	
 
    public Tiers(String nss, String nom, String prenom, String adress, Date datenaissance) {
       this.nss = nss;
       this.nom = nom;
       this.prenom = prenom;
       this.adress = adress;
       this.datenaissance = datenaissance;

    }
   
    public String getNss() {
        return this.nss;
    }
    
    public void setNss(String nss) {
        this.nss = nss;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getAdress() {
        return this.adress;
    }
    
    public void setAdress(String adress) {
        this.adress = adress;
    }
    public Date getDatenaissance() {
        return this.datenaissance;
    }
    
    public void setDatenaissance(Date datenaissance) {
        this.datenaissance = datenaissance;
    }
  

}


